source 'http://rubygems.org'

gem "rake", ">= 0.8.7"
gem 'rails', '3.0.7'
gem 'sqlite3'

gem 'delayed_job', '~> 2.0'
gem 'mimetype-fu', :require => 'mimetype_fu'

group :test do
  gem "cucumber-rails", :require => false
  gem "database_cleaner"
  gem 'capybara'
  gem "rspec-rails", ">= 2.0.1"
  gem "minitest-rails", ">= 0.2"
  gem "minitest-matchers", ">= 1.2"
  gem "email_spec", :path => "../../", :require => "email_spec"
end
