source 'http://rubygems.org'

gem 'sinatra'

group :test do
  gem 'cucumber'
  gem "cucumber-sinatra", :require => false
  gem 'pony'
  gem 'capybara'
  gem 'nokogiri'
  gem 'xpath'
  gem 'rspec'
  gem 'rack-test'
  gem "email_spec", :path => "../../", :require => "email_spec"
end
